### ISSUE TITLE
Email sent from old email address

### ISSUE THREAD

**Issue by josephmiclaus** [fhstp-mfg/couragiert#23]
Emails regarding new posts on the platform are being sent from an old email address. This should probably be changed to an "official" email address.

<img width="402" alt="screen shot 2017-01-13 at 15 57 33" src="https://cloud.githubusercontent.com/assets/4658706/21934273/1e63c3e0-d9a9-11e6-8e60-5cbfc4dcc094.png">

**Comment by doomsayer2** [comment]
Changed to couragiertegemeinde@gmail.com
