### ISSUE TITLE
Profile: Mobile Menu-Navigation

### ISSUE THREAD

**Issue by kblumenstein** [fhstp-mfg/couragiert#4]
![test](https://cloud.githubusercontent.com/assets/10909435/18677485/3f080b42-7f59-11e6-82bd-cc48b902da3c.jpg)

The menu item "Mobile Menu Options" is irritating. Should be not available for all users except Admin.

**Comment by doomsayer2** [comment]
Removed the Menu for the other users. Also other menus and plugins that are unnecessary to specific roles are removed.

**Edited:
Adminimize (new Plugin)**

_See:
[dev.couragiert.eu](url)_
