### ISSUE TITLE
Update Wordpress to 4.6.1?

### ISSUE THREAD

**Issue by kblumenstein** [fhstp-mfg/couragiert#5]
Can we update the system?

**Comment by doomsayer2** [comment]
I will try this on [test.couragiert.eu](url).
Before the recent changes will be always made on [dev.couragiert.eu](url) and than published to [couragiert.eu](url).

**Comment by doomsayer2** [comment]
I tried it out on [test.couragiert.eu](url) it's save but DON'T UPDATE the Theme for now. It will add a mobile menu by itself which conflicts with the mobile menu and can't be removed atm. I will try it on test but on dev only changes that will be pubilished are made. test is really to test out and fool around.
